/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// main.ts
var main_exports = {};
__export(main_exports, {
  default: () => MIDILogger
});
module.exports = __toCommonJS(main_exports);
var import_obsidian = require("obsidian");

// formatters.ts
var rawFormatter = {
  format(MIDInote, separator) {
    return `${MIDInote}${separator}`;
  }
};
var scientificFormatter = {
  format(MIDInote, separator) {
    const noteNames = ["C", "C#", "D", "D#", "E", "F", "F#", "G", "G#", "A", "A#", "B"];
    const noteName = noteNames[MIDInote % 12];
    const octave = Math.floor(MIDInote / 12) - 1;
    const noteString = `${noteName}${octave}${separator}`;
    return `${noteString}`;
  }
};
var ABCFormatter = {
  format(MIDInote, _separator) {
    const noteNames = ["C", "^C", "D", "^D", "E", "F", "^F", "G", "^G", "A", "^A", "B"];
    const noteName = noteNames[MIDInote % 12];
    const octave = Math.floor(MIDInote / 12) - 1;
    if (octave <= 4) {
      let outputText = `${noteName}`;
      for (let i = octave; i < 4; i++) {
        outputText += ",";
      }
      return `${outputText}`;
    } else {
      let outputText = `${noteName.toLowerCase()}`;
      for (let i = octave; i > 5; i--) {
        outputText += "'";
      }
      return `${outputText}`;
    }
  }
};

// main.ts
var DEFAULT_SETTINGS = {
  exportType: "scientific" /* Scientific */,
  separator: ","
};
var MIDILogger = class extends import_obsidian.Plugin {
  constructor() {
    super(...arguments);
    this.enabled = false;
  }
  writeNoteToEditor(note) {
    let noteString = "<UNKNOWN_FORMAT>";
    switch (this.settings.exportType) {
      case "raw" /* RawMessage */:
        noteString = rawFormatter.format(note, this.settings.separator);
        break;
      case "scientific" /* Scientific */:
        noteString = scientificFormatter.format(note, this.settings.separator);
        break;
      case "abc" /* ABC */:
        noteString = ABCFormatter.format(note, this.settings.separator);
        break;
    }
    const view = this.app.workspace.getActiveViewOfType(import_obsidian.MarkdownView);
    if (view) {
      const cursor = view.editor.getCursor();
      view.editor.replaceRange(noteString, cursor);
      view.editor.setCursor(cursor.line, cursor.ch + noteString.length);
    }
  }
  async enable() {
    try {
      this.midiAccess = await navigator.requestMIDIAccess();
      const inputs = this.midiAccess.inputs.values();
      for (let input of inputs) {
        input.onmidimessage = (msg) => {
          const [status, data1, data2] = msg.data;
          const command = status >> 4;
          const channel = status & 15;
          if (command === 9 && channel === 0) {
            const note = data1;
            const velocity = data2;
            if (velocity > 0) {
              this.writeNoteToEditor(note);
            }
          }
        };
      }
      new import_obsidian.Notice("MIDI Logger is active");
      this.mainStatusBar.setText("MIDI Logger is active");
      this.enabled = true;
    } catch (error) {
      new import_obsidian.Notice("Cannot open MIDI input port!");
    }
  }
  disable() {
    if (this.midiAccess) {
      const inputs = this.midiAccess.inputs.values();
      for (let input of inputs) {
        input.close();
      }
    }
    new import_obsidian.Notice("MIDI Logger is inactive");
    this.mainStatusBar.setText("");
    this.enabled = false;
  }
  async onload() {
    await this.loadSettings();
    this.mainStatusBar = this.addStatusBarItem();
    this.addRibbonIcon("music", "MIDI Logger", (evt) => {
      if (this.enabled) {
        this.disable();
      } else {
        this.enable();
      }
    });
    this.addCommand({
      id: "enable",
      name: "Start capture",
      checkCallback: (checking) => {
        if (!this.enabled) {
          if (!checking) {
            this.enable();
          }
          return true;
        }
        return false;
      }
    });
    this.addCommand({
      id: "disable",
      name: "Stop capture",
      checkCallback: (checking) => {
        if (this.enabled) {
          if (!checking) {
            this.disable();
          }
          return true;
        }
        return false;
      }
    });
    this.addCommand({
      id: "insert-abc-template",
      name: "Insert ABC template",
      editorCallback: (_editor, view) => {
        const ABC_TEMPLATE = [
          "```music-abc",
          "X:1",
          "T:Title",
          "M:4/4",
          "Q:1/4=90",
          "K:none",
          "",
          "```"
        ].join("\n");
        if (view) {
          const cursor = view.editor.getCursor();
          view.editor.replaceRange(ABC_TEMPLATE, cursor);
          view.editor.setCursor(cursor.line, cursor.ch + ABC_TEMPLATE.length);
        }
      }
    });
    this.addSettingTab(new MIDILoggerSettingTab(this.app, this));
  }
  onunload() {
    if (this.enabled) {
      this.disable();
    }
  }
  async loadSettings() {
    this.settings = Object.assign({}, DEFAULT_SETTINGS, await this.loadData());
  }
  async saveSettings() {
    await this.saveData(this.settings);
  }
};
var MIDILoggerSettingTab = class extends import_obsidian.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    new import_obsidian.Setting(containerEl).setName("Output format").setDesc("Choose the format of the MIDI note to be written to the editor").addDropdown((dropdown) => dropdown.addOptions({
      ["raw" /* RawMessage */]: "Raw message",
      ["scientific" /* Scientific */]: "Scientific",
      ["abc" /* ABC */]: "ABC"
    }).setValue(this.plugin.settings.exportType).onChange(async (value) => {
      this.plugin.settings.exportType = value;
      await this.plugin.saveSettings();
    }));
    new import_obsidian.Setting(containerEl).setName("Separator").setDesc("Separator between notes (only for raw and scientific formats)").addText((text) => text.setValue(this.plugin.settings.separator).onChange(async (value) => {
      this.plugin.settings.separator = value;
      await this.plugin.saveSettings();
    }));
  }
};

/* nosourcemap */